using System.Collections.Immutable;

namespace ObjectiveIron.Core.Models.Primitives;

/// <summary>
/// Represents a Clausewitz script block — a named collection of properties and nested blocks.
/// This is the fundamental AST node for triggers, effects, modifiers, and any grouped content.
/// 
/// Example Clausewitz:
/// <code>
/// completion_reward = {
///     add_political_power = 150
///     hidden_effect = {
///         country_event = { id = my.1 days = 5 }
///     }
/// }
/// </code>
/// </summary>
public sealed class Block
{
    /// <summary>
    /// Ordered entries in this block. Each entry is either a Property or a nested named Block.
    /// </summary>
    public ImmutableList<BlockEntry> Entries { get; init; } = ImmutableList<BlockEntry>.Empty;

    public Block() { }

    public Block(IEnumerable<BlockEntry> entries)
    {
        Entries = entries.ToImmutableList();
    }

    public Block WithEntry(BlockEntry entry) =>
        new() { Entries = Entries.Add(entry) };

    public Block WithEntries(IEnumerable<BlockEntry> entries) =>
        new() { Entries = Entries.AddRange(entries) };
}

/// <summary>
/// A single entry inside a Block — either a key=value property or a named sub-block.
/// </summary>
public abstract record BlockEntry
{
    /// <summary>A key = value property (e.g., add_political_power = 150)</summary>
    public sealed record PropertyEntry(Property Property) : BlockEntry;

    /// <summary>A named sub-block (e.g., hidden_effect = { ... })</summary>
    public sealed record NestedBlock(string Name, Block Block, Operator Operator = Operator.Equals) : BlockEntry;

    /// <summary>A comment line (e.g., # This is generated by ObjectiveIron)</summary>
    public sealed record Comment(string Text) : BlockEntry;
}
